Players should be able to resume an in progress Tic Tac Toe game.
WasanMoosa/TIC_TAC_TOE pull request #14
Opened 2023-01-04 08:15 UTC by WasanMoosa

file

2023-01-04 10:04 UTC, BaraahAlKalbani commented on TICTAC/src/TICTACWithResumeFile.java
> +						if (i < 3) {
use meaningful var names instead of i

2023-01-04 10:11 UTC, BaraahAlKalbani requested changes
Great code by the way but change the some variables names to meaningful ones

2023-01-04 10:34 UTC, WasanMoosa commented on TICTAC/src/TICTACWithResumeFile.java
> +						if (i < 3) {
Okay

2023-01-04 10:47 UTC, BaraahAlKalbani approved these changes

2023-01-08 05:57 UTC, FatemaAlbalushi reviewed
Great work.

2023-01-08 05:57 UTC, FatemaAlbalushi commented on TICTAC/src/TICTACWithResumeFile.java
> -//////////////////////////////////////////////////////////////////////////////////////////////////////////////
Try to generate java dox.

2023-01-08 05:57 UTC, FatemaAlbalushi commented on TICTAC/src/TICTACWithResumeFile.java
Remove the unused spacing

2023-01-08 05:57 UTC, FatemaAlbalushi commented on TICTAC/src/TICTACWithResumeFile.java
> -		int j= moveInt%3;
Instead of using i,j try to use meaningful name.

2023-01-08 06:29 UTC, FatemaAlbalushi approved these changes

2023-01-08 07:20 UTC, AnwaarAlbusaidi approved these changes
great work

2023-01-08 07:23 UTC, merged